# Generated by Django 6.0.3 on 2026-04-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
